version: '3'
services:
  postgres:
    image: postgres:10.0-alpine
    env_file: .env
    volumes:
      - pg-data-volume:/var/lib/postgresql/data
    ports:
      - '8765:5432'

volumes:
  pg-data-volume: